competitions/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from wp_highscores.rest_views import ScoreTableViewSet, ScoreEntryViewSet
from wp_submission.rest_views import SubmissionViewSet, RunViewSet
from wp_submission.views import CompetitionHome

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'submissions', SubmissionViewSet)
router.register(r'runs', RunViewSet)
router.register(r'highscore', ScoreTableViewSet)
router.register(r'highscore-entry', ScoreEntryViewSet)

urlpatterns = [
    url(r'^$', CompetitionHome.as_view(), name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^competitions/', include('wp_submission.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wp_submission/urls.py
from django.conf.urls import url, include
from views import CompetitionList, SubmissionEdit, SubmissionDetail, CompetitionUpload, CompetitionRunDetail, SimpleRegister, CompetitionDetail, CompetitionDashboard, CompetitionSubmit, SubmissionHistory

urlpatterns = [

    url(r'^$', CompetitionList.as_view(), name='competition_list'),
    url(r'^details/(?P<slug>[\w-]+)$', CompetitionDetail.as_view(), name='competiton_detail'),

    url(r'^run-details/(?P<pk>\d+)$', CompetitionRunDetail.as_view(), name='run_detail'),
    url(r'^sign-up/(?P<run>\d+)$', CompetitionSubmit.as_view(), name='register'),

    url(r'^db$', CompetitionDashboard.as_view(), name='dashboard'),

    url(r'^submit$', CompetitionSubmit.as_view(), name='submission_create'),
    url(r'^submit/(?P<run>\d+)$', CompetitionSubmit.as_view(), name='submission_create'),





    url(r'^submissions/(?P<pk>\d+)/edit$', SubmissionEdit.as_view(), name='submission_edit'),
    url(r'^submissions/(?P<submission>\d+)/upload$', CompetitionUpload.as_view(), name='submission_upload'),

    url(r'^r$', SimpleRegister.as_view(), name='register'),


    url(r'^submissions/v/(?P<pk>\d+)/$', SubmissionDetail.as_view(), name='submission_detail'),
    url(r'^submissions/$', SubmissionHistory.as_view(), name='submission_view'),
    url(r'^submissions/u/(?P<user>\d+)$', SubmissionHistory.as_view(), name='submission_view')
]

wp_submission/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils import timezone

import os

STATUS_LIST = [
    ("BP", "Build pending"),
    ("BF", "Build failed"),
    ("BS", "Build succeded")
]

class Competition(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    specification_url = models.URLField(blank=True)
    rules_url = models.URLField(blank=True)
    samples_url = models.URLField(blank=True)
    guidelines_url = models.URLField(blank=True)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('competiton_detail', kwargs={'slug':self.slug})

    def __unicode__(self):
        return self.name

class RunManager(models.Manager):

    def get_queryset(self):
        qs = super(RunManager, self).get_queryset()
        return qs

    def get_reg_closed(self):
        """Runs which people can no longer register for"""
        qs = super(RunManager, self).get_queryset()
        qs = qs.exclude(registration_deadline__gt=timezone.now())
        return qs

    def get_reg_open(self):
        """Runs which people can still register for"""
        qs = super(RunManager, self).get_queryset()
        qs = qs.exclude(registration_deadline__lte=timezone.now())
        return qs

class CompetitionRun(models.Model):
    name = models.CharField(max_length=100)
    competition = models.ForeignKey(Competition)
    registration_deadline = models.DateTimeField(blank=True, null=True)
    sumission_deadline = models.DateTimeField(blank=True, null=True)
    objects = RunManager()

    def is_registered(self, user):
        return self.submission_set.filter(user=user).exists()

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('run_detail', kwargs={'pk':self.pk})

    @property
    def can_register(self):
        if self.registration_deadline:
            return timezone.now() < self.registration_deadline
        else:
            return True

    def __unicode__(self):
        return "%s" % (self.name)

    class Meta:
        ordering = ["-registration_deadline", "sumission_deadline"]

class SubmissionManager(models.Manager):

    def get_queryset(self):
        qs = super(SubmissionManager, self).get_queryset()
        qs = qs.exclude(run__registration_deadline__lte=timezone.now())
        return qs


class Submission(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    run = models.ForeignKey(CompetitionRun)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    created = models.DateTimeField(auto_now_add=True)
    ranking = models.FloatField(default=1500)
    ranking_rd = models.FloatField(default=350)
    objects = SubmissionManager()

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('submission_detail', kwargs={'pk':self.pk})

    def is_owner(self, user):
        return self.user == user

    @property
    def score(self):
        return "{0} ({1})".format(self.ranking, self.ranking_rd)

    @property
    def current_upload(self):
        return self.uploads.first()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["ranking", "ranking_rd"]
        unique_together = ( ("user","run") )


def submission_path(instance,filename):
    user_ext = os.path.splitext(filename)[1]
    return 'submissions/{0}/{1}{2}'.format(instance.submission.run.pk, instance.user.username, user_ext)

class SubmissionEntry(models.Model):
    submission = models.ForeignKey(Submission, related_name="uploads")
    status = models.CharField(max_length=5, default="BP", choices=STATUS_LIST)
    created = models.DateTimeField(auto_now_add=True)
    upload = models.FileField(upload_to=submission_path)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('submission_detail', kwargs={'pk':self.submission.pk})

    def __unicode__(self):
        return "{1}".format(self.created, self.upload)

    class Meta:
        ordering = ["-created"]

wp_submission/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import CompetitionRun, Submission, SubmissionEntry

class RegisterForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(RegisterForm, self).__init__(*args, **kwargs)

    def clean(self):
        if "run" not in self.cleaned_data:
            raise ValidationError("Invalid run provided")

        run = self.cleaned_data['run']
        if not run.can_register:
            raise ValidationError("registrations are not currently open")

        if run.is_registered(self.user):
            raise ValidationError("You already have a submission")

    class Meta:
        fields = ["name", "description", "run"]
        widgets = {'run': forms.HiddenInput()}
        model = Submission

class UploadForm(forms.ModelForm):

    class Meta:
        fields = ["submission", "upload"]
        model = SubmissionEntry

wp_submission/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth import get_user_model
from django import forms
from django.core.urlresolvers import reverse_lazy
from django.core.exceptions import PermissionDenied

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Competition, CompetitionRun, Submission, SubmissionEntry
from .forms import RegisterForm, UploadForm

# Create your views here.
class CompetitionHome(ListView):
    """Display infomation about the current competitions"""
    model = Competition
    context_object_name = "competition_list"
    template_name = "wp_submission/home.html"

class CompetitionList(ListView):
    """List the currently running competitions"""
    model = Competition
    context_object_name = "competition_list"

class CompetitionDetail(ListView):
    """List the currently running competitions"""
    model = CompetitionRun
    context_object_name = "run_list"
    paginate_by = 5

    def get_queryset(self, **kwargs):
        qs = super(CompetitionDetail, self).get_queryset(**kwargs)
        req_competition = self.kwargs.get('slug', None)
        return qs.filter(competition__slug=req_competition)

    def get_context_data(self, **kwargs):
        context = super(CompetitionDetail, self).get_context_data(**kwargs)
        req_competition = self.kwargs.get('slug', None)
        context['competition'] = get_object_or_404(Competition, slug=req_competition)
        return context

class CompetitionRunDetail(DetailView):
    """List details about a competition run"""
    model = CompetitionRun
    context_object_name = "run"

@method_decorator(login_required, name='dispatch')
class CompetitionSubmit(CreateView):
    model = Submission
    form_class = RegisterForm

    def get_form_kwargs(self):
        kwargs = super(CompetitionSubmit, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CompetitionSubmit, self).get_context_data(**kwargs)
        run_id = self.kwargs.get('run')
        context['run'] = get_object_or_404(CompetitionRun, id=run_id)
        return context

    def get_initial(self):
        context = super(CompetitionSubmit, self).get_initial()
        context['run'] = self.kwargs.get('run', None)
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CompetitionSubmit, self).form_valid(form)

@method_decorator(login_required, name='dispatch')
class CompetitionUpload(CreateView):
    form_class = UploadForm
    template_name = "wp_submission/submissionentry_form.html"

    def get_context_data(self, **kwargs):
        context = super(CompetitionUpload, self).get_context_data(**kwargs)
        run_id = self.kwargs.get('submission')
        context['submission'] = get_object_or_404(Submission, id=run_id)

        # if the user is not the owner of that submission, tell them off
        if not context['submission'].user == self.request.user:
            raise PermissionDenied()

        return context

    def get_initial(self):
        context = super(CompetitionUpload, self).get_initial()
        context['submission'] = self.kwargs.get('submission', None)
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CompetitionUpload, self).form_valid(form)

@method_decorator(login_required, name='dispatch')
class SubmissionEdit(UpdateView):
    model = Submission
    fields = ["name","description"]

    def get_context_data(self, **kwargs):
        context = super(SubmissionEdit, self).get_context_data(**kwargs)
        #req_competition = self.kwargs.get('submission', None)
        #context['submission'] = get_object_or_404(Submission, id=req_user)
        return context

    def get_object(self, *args, **kwargs):
        obj = super(SubmissionEdit, self).get_object(*args, **kwargs)
        # if this user did not create the submission, tell them off
        if not obj.user == self.request.user:
            raise PermissionDenied()
        return obj

    def get_initial(self):
        context = super(SubmissionEdit, self).get_initial()
        context['run'] = self.kwargs.get('run', None)
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(SubmissionEdit, self).form_valid(form)

class SubmissionDetail(DetailView):
    """Show details about a given submission"""
    model = Submission
    context_object_name = "submission"

class SubmissionHistory(ListView):
    """A history of a given user's submissions"""
    model = Submission
    context_object_name = "submission_list"

    def get_queryset(self):
        qs = super(ListView, self).get_queryset()
        req_user = self.kwargs.get('user', None)
        if req_user:
            User = get_user_model()
            self.participant = get_object_or_404(User, id=req_user)
        else:
            self.participant = self.request.user
        return qs.filter(user=self.participant)

    def get_context_data(self, **kwargs):
        context = super(SubmissionHistory, self).get_context_data(**kwargs)
        context['participant'] = self.participant
        return context

@method_decorator(login_required, name='dispatch')
class CompetitionDashboard(ListView):
    model = CompetitionRun
    context_object_name = "run_list"
    template_name = "wp_submission/user_dashboard.html"

    def get_queryset(self):
        return Submission.objects.filter(user__pk=self.request.user.pk)

@method_decorator(login_required, name='dispatch')
class SimpleRegister(FormView):
    template_name = "wp_submission/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy('dashboard')

    def get_initial(self):
        context = super(SimpleRegister, self).get_initial()
        context['run'] = self.kwargs.get('run', None)
        return context

    def form_valid(self, form):
        run = form.cleaned_data['run']
        run.participants.add(self.request.user)
        return super(SimpleRegister, self).form_valid(form)

wp_submission/templates/wp_submission/competition_list.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
<h1>Competition List</h1>
<p class="lead">This is a list of competitions which are run using this system.</p>
</div>

{% for competition in competition_list %}
	<h2><a href="{% url 'competiton_detail' slug=competition.slug %}">{{competition}}</a></h2>
	<p>{{competition.description}}</p>


	<table class="table">
		<thead>
		<tr>
			<th>Run</th>
			<th>Registration Deadline</th>
			<th>Submission Deadline</th>
			<th>Actions</th>
		</tr>
		</thead>
		<tbody>
		{% for run in competition.competitionrun_set.all %}
			<tr>
				<th>{{run.name}}</th>
				<td>{{run.registration_deadline}}</td>
				<td>{{run.sumission_deadline}}</td>
				<td><a href="{% url 'register' run=run.pk %}">Register</a></td>
			</tr>
			{% empty %}
			<tr>
				<td colspan="4">No active runs</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endfor %}
{% endblock content %}

wp_submission/templates/wp_submission/competitionrun_detail.html
{% extends "base_multicol.html" %}

{% block title %}{{run}}{% endblock %}

{% block head %}
<ol class="breadcrumb">
	<li><a href="{% url "home" %}">home</a></li>
  <li><a href="{{ run.competition.get_absolute_url }}">{{run.competition}}</a></li>
  <li><a href="{{ run.get_absolute_url }}">{{run.name}}</a></li>
</ol>

<div class="page-header">
	<h1>{{run.competition}} <small>{{run.name}}</small></h1>
</div>
{% endblock %}

{% block content %}
<p>{{competition.description|safe}}</p>

{% if run.can_register %}
<div class="alert alert-info">
Registrations open
</div>
{% else %}
<div class="alert alert-info">
Registrations closed
</div>
{% endif %}

<table class="table table-striped">
	<thead>
	<tr>
		<th>Entry</th>
		<th>Country</th>
		<th>Points</th>
	</tr>
</thead>
<tbody>
	{% for entry in run.submission_set.all %}
	<tr>
		<td><a href="{{ entry.get_absolute_url }}">{{entry}}</a>
			{% if entry.sample %}
				<span class="label label-default">sample</span>
			{% endif %}
		</td>
		<td>United Kingdom</td>
		<td>{{entry.score}}</td>
	</tr>
	{% endfor %}
</tbody>
<caption>Run #10 - Last updated 10/02/2016</caption>
</table>
<a href="#" class="pull-right">More detail</a>

{% endblock %}

{% block actions %}
<div class="list-group">
	<a href="{% url "submission_detail" pk=1 %}" class="list-group-item">My Controller</a>
	<a href="{% url "submission_create" run=run.pk %}" class="list-group-item">Submit Controller</a>
	<a href="#" class="list-group-item">View scores</a>

	{% if competition.specification_url %}
	<a href="{{competition.specification_url}}" class="list-group-item">View spesification</a>
	{% endif %}
	{% if competition.rules_url %}
	<a href="{{competition.rules_url}}" class="list-group-item">View rules</a>
	{% endif %}
	{% if competition.samples_url %}
	<a href="{{competition.samples_url}}" class="list-group-item">View sample controllers</a>
	{% endif %}
	{% if competition.guidelines_url %}
	<a href="{{competition.guidelines_url}}" class="list-group-item">View submission guidelines</a>
	{% endif %}
</div>
{% endblock actions %}

wp_submission/templates/wp_submission/competitionrun_list.html
{% extends "base_multicol.html" %}
{% load humanize %}

{% block head %}
<div class="page-header">
	<h1>{{competition.name}}</h1>
</div>
{% endblock %}

{% block content %}
<p>{{competition.description|safe}}</p>

<h2>Open Runs</h2>
<table class="table table-striped">
	<thead>
	<tr>
		<th>Name</th>
		<th>Registration Deadline</th>
		<th>Submission Deadline</th>
		<th>Register</th>
	</tr>
	</thead>

	<tbody>
	{% for run in run_list %}
	<tr>
		<th><a href="{% url 'run_detail' pk=run.pk %}">{{run.name}}</a></th>
		<td title="{{run.registration_deadline}}">{{run.registration_deadline|naturaltime|default:"N/A"}}</td>
		<td title="{{run.sumission_deadline}}">{{run.sumission_deadline|naturaltime|default:"N/A"}}</td>
		<td>{% if run.can_register %}<a class="btn btn-default btn-sm" href="{% url 'register' run=run.pk %}">Sign up</a>{% else %}Registration Closed{% endif %}</td>
	</tr>
	{% empty %}
	<tr>
		<td colspan="4">No runs currently planned</td>
	</tr>
	{% endfor %}
	</tbody>
</table>

{% include "bootstrap/pagination.html" %}
{% endblock %}

{% block actions %}
<div class="list-group">
	{% if competition.specification_url %}
	<a href="{{competition.specification_url}}" class="list-group-item">View spesification</a>
	{% endif %}
	{% if competition.rules_url %}
	<a href="{{competition.rules_url}}" class="list-group-item">View rules</a>
	{% endif %}
	{% if competition.samples_url %}
	<a href="{{competition.samples_url}}" class="list-group-item">View sample controllers</a>
	{% endif %}
	{% if competition.guidelines_url %}
	<a href="{{competition.guidelines_url}}" class="list-group-item">View submission guidelines</a>
	{% endif %}
</div>

<div class="list-group">
	<a href="#" class="list-group-item">Previous runs</a>
	<a href="#" class="list-group-item">Future runs</a>
</div>
{% endblock actions %}

wp_submission/templates/wp_submission/home.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to the Competition Server</h1>
<p class="lead">This website allows you to view and submit entries for
competitions.</p>

{% for competition in competition_list %}
<div class="media">
  <div class="media-left">
    <img class="media-object" src="http://www.pacmanvghosts.co.uk/images/game/ex1.png" style="width: 150px;" alt="...">
  </div>
  <div class="media-body">
    <h1 class="media-heading"><a href="{{competition.get_absolute_url}}">{{competition}}</a></h1>
    {{competition.description}}
  </div>
</div>
{% endfor %}

{% endblock %}

wp_submission/templates/wp_submission/register.html
{% extends "base.html" %}

{% block content %}
<h1>Competition Registration</h1>


<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>
{% endblock content %}

wp_submission/templates/wp_submission/submission_detail.html
{% extends "base_multicol.html" %}
{% load humanize %}

{% block head %}
<ol class="breadcrumb">
	<li><a href="{% url "home" %}">home</a></li>
  <li><a href="{{ submission.run.competition.get_absolute_url }}">{{submission.run.competition}}</a></li>
  <li><a href="{{ submission.run.get_absolute_url }}">{{submission.run}}</a></li>
	<li><a href="{{ submission.get_absolute_url }}">{{submission}}</a></li>
</ol>

<div class="page-header">
	<h1>{{submission.name}}</h1>
</div>
{% endblock %}

{% block content %}
{% if submission.description %}
<p>{{submission.description}}.</p>
{% else %}
<p class="text-muted">No description provided</p>
{% endif %}

<h2>Summary</h2>
<dl class="dl-horizontal">
	<dt>Run ID</dt>
	<dd><a href="{{ submission.run.get_absolute_url }}">{{submission.run}}</a></dd>
	<dt>Language</dt>
	<dd>Java</dd>
	<dt>First upload</dt>
	<dd>{{submission.created}}</dd>
	<dt>Last modified</dt>
	<dd>{{submission.created}}</dd>
	<dt>Sample Controller?</dt>
	<dd>No</dd>
</dl>

<h2>Versions</h2>
<table class="table table-striped">
	<thead>
	<tr>
		<th>Date</th>
		<th>Status</th>
		<th>Size</th>
	</tr>
	</thead>

	<tbody>
	{% for run in submission.uploads.all %}
	<tr>
		<th>{{run.created}}</th>
		<td>{{run.get_status_display}}</td>
		<td>{{run.upload.size|filesizeformat}}</td>
	</tr>
	{% empty %}
	<tr>
		<td colspan="3">No previous versions</td>
	</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}

{% block actions %}
<div class="list-group">
	<a href="{{submission.submission}}" class="list-group-item">Download code</a>
	<a href="#" class="list-group-item">View paper</a>
</div>

<div class="list-group">
	<a href="{% url "submission_upload" submission=submission.pk %}" class="list-group-item">Upload new version </a>
	<a href="{% url "submission_edit" pk=submission.pk %}" class="list-group-item">Edit Submission</a>
</div>
{% endblock actions %}

wp_submission/templates/wp_submission/submission_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<ol class="breadcrumb">
	<li><a href="{% url "home" %}">home</a></li>
  <li><a href="{{ run.competition.get_absolute_url }}">{{run.competition}}</a></li>
  <li><a href="{{ run.get_absolute_url }}">{{run.name}}</a></li>
</ol>

<div class="page-header">
  <h1>{{run}}</h1>
</div>

<div class="well">
	<h2>Submission Details</h2>

<form action="#" method="post">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" class="btn btn-primary" value="Create" />
</form>
</div>
{% endblock content %}

wp_submission/templates/wp_submission/submission_list.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
<h1>{{user}}'s submissions</h1>

<table class="table table-hover">
	<caption>Previous Submissions</caption>
	<thead>
	<tr>
		<th>Run</th>
		<th>Date</th>
		<th>Status</th>
		<th>Download</th>
	</tr>
	</thead>
	<tbody>
	{% for submission in submission_list %}
	<tr>
		<td><a href="{{ submission.get_absolute_url }}">{{submission.run}}</a></td>
		<td title="{{submission.created}}">{{submission.created|naturaltime}}</td>
		<td>{{submission.get_status_display}}</td>
		<td><a href="{{submission.submission.url}}">Download</a></td>
	</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock content %}

wp_submission/templates/wp_submission/submissionentry_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<ol class="breadcrumb">
	<li><a href="{% url "home" %}">home</a></li>
  <li><a href="{{ submission.run.competition.get_absolute_url }}">{{submission.run.competition}}</a></li>
  <li><a href="{{ submission.run.get_absolute_url }}">{{submission.run}}</a></li>
</ol>

<div class="page-header">
  <h1>{{submission}}</h1>
</div>

<div class="well">
	<h2>Submission Details</h2>

<form action="#" enctype="multipart/form-data" method="post">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" class="btn btn-primary" value="Create" />
</form>
</div>
{% endblock content %}

wp_submission/templates/wp_submission/user_competitions.html
{% extends "base.html" %}

{% block content %}
<h1>Competition List</h1>

<ul>
	{% for run in run_list %}
	<li>{{run}} <a href="{% url 'submission_create' run=run.pk %}">submit</a></li>
	{% empty %}
	<li>You do not have any competitions</li>
	{% endfor %}
</ul>


<a href="{% url 'runs_view' %}">View competitions</a>
<a href="{% url 'submission_create' %}">Upload new entry</a>
{% endblock content %}

wp_submission/templates/wp_submission/user_dashboard.html
{% extends "base_multicol.html" %}

{% block head %}
<ol class="breadcrumb">
	<li><a href="{% url "home" %}">home</a></li>
  <li><a href="{{ submission.run.competition.get_absolute_url }}">Dashboard</a></li>
</ol>

<div class="page-header">
<h1>Competition Overview</h1>
</div>
{% endblock %}

{% block content %}

<table class="table table-striped">
  <caption>Currently active submissions</caption>
	<thead>
		<tr>
			<th>Submission</th>
			<th>Run</th>
			<th>Closing Date</th>
		</tr>
	</thead>
	<tbody>

	{% for run in run_list %}
		<tr>
			<th><a href="{{ run.get_absolute_url }}">{{run}}</a></th>
			<td><a href="{{ run.get_absolute_url }}">{{run.run}}</a></td>
			<td>{{run.run.sumission_deadline}}</td>
		</tr>
	{% empty %}
	<li>You do not have any competitions</li>
	{% endfor %}
	</tbody>
</table>
{% endblock content %}

{% block actions %}
<div class="list-group">
	<a class="list-group-item" href="{{ run.competition.get_absolute_url }}">View competitions</a></li>
	<a class="list-group-item" href="{% url 'submission_view' %}">View submissions</a></li>
</div>

<div class="list-group">
	<a class="list-group-item" href="{% url 'submission_create' %}">Create new Submission</a></li>
	<a class="list-group-item" href="{% url 'submission_view' %}">View submissions</a></li>
</div>
{% endblock %}